apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app-2
  namespace: demo
  labels:
    app: gitops-demo-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gitops-demo-2
  template:
    metadata:
      labels:
        app: gitops-demo-2
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:0.3
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
